### ISSUE TITLE
Investigate how to migrate workflow jobs from one Environment to another

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7-dbx#120]
Is it possible to "export" the jobs configuration on one environment and "Import" them on another?

Need to have in mind that values for the parameters passed will be different from one env. to another - how can we achieve this without having to manually change them on each env.? can they be read from a file? can they be environment variables on the given environment?

**Comment by ugx2** [comment]
I have found these two ways to promote existing workflows to a different environment.

1. Using Datbricks CLI as part of CI/CD
https://medium.com/@maciej.skorupka/promoting-azure-databricks-workflows-using-cli-whats-the-format-a7ff86ee3f7

2. Using Terraform IaC
https://www.databricks.com/blog/2022/12/20/reuse-existing-workflows-through-terraform.html
