### ISSUE TITLE
Databricks table/view with consolidated view on errors/warnings

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7-dbx#126]
We need to consolidate all issues (errors and warnings) generated for both Structure and MMG Validation into a single table or view per program in GOLD

![image](https://user-images.githubusercontent.com/3239945/226975909-bddeafc3-2879-4312-9301-1af9bd062140.png)

**Comment by ugx2** [comment]
Met with Marceclo and Neelima.
We are going to combine structure and mmg validation in silver and add "process name" column.
Rename to hl7_validation_report_silver and we are going to have gold tables out of this new silver table.
