### ISSUE TITLE
CREATE TST Database

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7-dbx#30]
Create a Test Database: ocio_dex_tst

Location: ocioededatalakedbr / ocio-dex-tst

**Comment by raman-cdc** [comment]
Test Database ocio_dex_tst created writing to DEX DEV Storage Account in a new container

**Comment by raman-cdc** [comment]
Created Test DB ocio_dex_tst
Valiated R/W access with a test data

**Comment by mscaldas2012** [comment]
In order to hit the deadline of Tues, since we don't have yet a full TST pipeline, we will create a temp db:
   ocio_dex_prog_dev
   
That temp db will have views with exact same names as our gold tables from ocio_dex_dev .
That way we can grant access to program users to a separate database while we finish up the TST Azure environment.

The only impact is data will dynamically change on those views, But we can manage this with developers being aware that programs are using data. Also, static tables can be created on the temp database with snapshots of current gold tables if needed.
