### ISSUE TITLE
Use Vault to host event hub keys 

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7-dbx#35]
Need Vault set up to read event hub key. Vault should be associated to DBX cluster via scopes. (EDAV Ticket)

EDAV Ticket:
 - Create DEX-DBX-DEV-KV
     Add  DatabricksPolicyKeyValue from DEV
     Associate this KV with DEV clsuter

- Create DEX-DBX-TST-KV
     Add  DatabricksPolicyKeyValue from TST
     Associate this KV with TST cluster

* [ ] Use the same Event Hub Shared Access Policy Name on all Environments. (DevOps ticket for Terraform)
* [ ] Use same Vault key name on all environments.

**Comment by raman-cdc** [comment]
Used the existing Key Vault ("DEX-DEV-Vault" ) provided by EDAV team and created Secrets for DEV Eventhub namespace
Modified config file to read from values from Key Vault  for Eventhub namespace

TEST Eventhub not created yet.
