### ISSUE TITLE
Create KeyVaults for each environment. Use same key names on all Environments.

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7-dbx#46]
get a Specific KeyVault/Scope per environment and use same key names on all environments.

Instead of a global scope (dbs-scope-dex), we should have 
* dbs-scope-dex-dev, 
* dbs-scope-dex-tst, 
* dbs-scope-dex-stg, 
* dbs-scope-dex-prod

**Plan B: If we cant have separate scopes/keyvaults per Environment, make sure we use same Key names on keyvault with a PREFIX or Suffix like DEV_{keyname} and TST_{keyname}**

and instead of env. specific keys (with -dev- in their names) we should have global key names: 
ex.: tf-eh-namespace-key, tf-eh-namespace-key-val.

As a matter of fact we should not need tf-eh-namespace-key - that should be created as the same name on all environments (ex. : **DatabricksSharedPolicy**) and all we should need to configure is tf-eh-namespace-key-value

**Comment by lmcnabb** [comment]
@raman-cdc estimate pls

**Comment by raman-cdc** [comment]
Scope is defined within Databricks by EDAV team and Key Vault is defined within Azure 
1. EDAV Team wants to have one Scope (dbs-scope-DEX) for DEV/TEST and may be another for STG/PROD
2. EDAV Team wants to have one KeyVault for  DEV/TEST and another for STG/PROD.

Sent email to EDAV team asking for their future guidance on these.


We might end up using Plan B.

Also the Terraform script might need to be updated to include environment as prefix or suffix

**Comment by raman-cdc** [comment]
EDAV agreed to create a separate scope for each environment. They have yet to prioritize the changes for the same.

**Comment by raman-cdc** [comment]
Scopes created with below names
DBS-SCOPE-DEX-DEV
DBS-SCOPE-DEX-TST
DBS-SCOPE-DEX-STG
DBS-SCOPE-DEX-PRD

Global KeyVault secret created to be used across all environments

-    ocio-ede-eh-namespace-key-name
-    ocio-ede-eh-namespace-key-val


Pull Request #83
