### ISSUE TITLE
Setting up a new TST environment

### ISSUE THREAD

**Issue by raman-cdc** [CDCgov/data-exchange-hl7-dbx#56]
- [ ] Setting up new Test environment in Azure and Databricks

- [ ]  Execute  DEX pipeline and Validate results in TST environment

**Comment by raman-cdc** [comment]
Storage issues are resolved
SQL End point cannot read tables in a database. 
 Service Principal Requires Storage Blob Data Contributor role on  Storage account

**Comment by mscaldas2012** [comment]
Under Review phase - Validation done by Friday 2/24
